name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Uncomment the following section to enable parallel runs:
    # strategy:
    #   fail-fast: false  # Prevents stopping all parallel jobs if one fails
    #   matrix:
    #     containers: [1, 2]  # This will create 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
